name: build
on:
- push
- pull_request
- workflow_dispatch
env:
   MAVEN_OPTS: -Xmx1g
jobs:
   build:
      runs-on: ubuntu-latest
      steps:
      -  name: Set up JDK 17
         uses: actions/setup-java@v3
         with:
            distribution: 'zulu'
            java-version: |
             11
             17
      -  name: Cache SonarCloud packages
         uses: actions/cache@v3
         with:
            path: ~/.sonar/cache
            key: ${{ runner.os }}-sonar
            restore-keys: ${{ runner.os }}-sonar
      -  name: Cache Maven packages
         uses: actions/cache@v3
         with:
            path: ~/.m2
            key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-m2
      -  name: maven-settings-xml-action
         uses: whelk-io/maven-settings-xml-action@v21
         with:
           repositories: '[{ "id": "repository.spring.milestone", "url": "https://repo.spring.io/milestone" }]'
           plugin_repositories: '[{ "id": "repository.spring.milestone", "url": "https://repo.spring.io/milestone" }]'
      -  uses: actions/checkout@v3
      -  name: Build with Maven
         run: mvn --batch-mode clean verify -Pcdc,it -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn
      -  uses: codecov/codecov-action@v3
      -  name: Analyse
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         run: mvn org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.organization=doudouchat -Dsonar.projectKey=doudouchat_exemple-cdc -Dsonar.host.url=https://sonarcloud.io -Dsonar.java.jdkHome=${JAVA_HOME_11_X64}
      -  name: display logs cassandra 1
         if: ${{ always() }}
         run: cat exemple-cdc-agent/target/.logs/cassandra_1/archive/*.log
      -  name: display logs cassandra 2
         if: ${{ always() }}
         run: cat exemple-cdc-agent/target/.logs/cassandra_2/archive/*.log
      -  uses: codecov/codecov-action@v3